/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package spread.sheet.reader

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'spread.sheet.reader.greeting' plugin.
 */
class SpreadSheetReaderPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("spread.sheet.reader.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
